// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4eYenY4qBZrGMRTgvrk0XAYkSi1OVB4I',
    appId: '1:856621495576:web:894e694c7216fcfea31a6d',
    messagingSenderId: '856621495576',
    projectId: 'chatapp-b11f9',
    authDomain: 'chatapp-b11f9.firebaseapp.com',
    storageBucket: 'chatapp-b11f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_aDbCSGc7l9ylcNuv_K7UCavCsqBN2k',
    appId: '1:856621495576:android:344035660d3bdf19a31a6d',
    messagingSenderId: '856621495576',
    projectId: 'chatapp-b11f9',
    storageBucket: 'chatapp-b11f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABWDkfpj-KarIRm_VB1WYxwrtbmE_0WLc',
    appId: '1:856621495576:ios:2718351dc7211a95a31a6d',
    messagingSenderId: '856621495576',
    projectId: 'chatapp-b11f9',
    storageBucket: 'chatapp-b11f9.appspot.com',
    iosBundleId: 'com.example.miniMes',
  );
}
